from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton


leave_request_button = InlineKeyboardButton(text='📛Оставить заявку', callback_data='leave_req')
share_an_offer_button = InlineKeyboardButton(text='💡Поделиться предложением', callback_data='share_offer')
back_button = InlineKeyboardButton(text='⬅️Назад', callback_data='back')
pass_button = InlineKeyboardButton(text='▶Пропустить', callback_data='pass')
call_me_button = InlineKeyboardButton(text='📞Перезвоните мне', callback_data='call_me')
write_me_button = InlineKeyboardButton(text='📞Свяжитесь со мной в чат-боте', callback_data='write_me')
yes_button = InlineKeyboardButton(text='✅Да', callback_data='yes')
close_dialog_button = InlineKeyboardButton(text='❌📞Завершить диалог', callback_data='close_dialog')
change_name_button = InlineKeyboardButton(text='🛠Поменять имя', callback_data='change_name')
change_phone_button = InlineKeyboardButton(text='🛠Сменить номер', callback_data='change_phone')
mailing_button = InlineKeyboardButton('✉️Рассылка всем пользователям', callback_data='mailing')
info_user_button = InlineKeyboardButton('🗄📂Информация о пользователях', callback_data='info_user')
block_button = InlineKeyboardButton('❌❌Блокировка пользователей', callback_data='block')
home_button = InlineKeyboardButton('🏠В Главное меню', callback_data='home')
block_user_button = InlineKeyboardButton('❌Заблокировать пользователя', callback_data='block_user')
unlock_user_button = InlineKeyboardButton('✅Разблокировать пользователя', callback_data='unlock_user')

main_request_keyboard = InlineKeyboardMarkup(row_width=2).add(leave_request_button, share_an_offer_button, back_button)
pass_keyboard = InlineKeyboardMarkup(row_with=1).add(pass_button, back_button)
back_keyboard = InlineKeyboardMarkup(row_width=1).add(back_button)
connection_method_keyboard = InlineKeyboardMarkup(row_width=1).add(call_me_button, write_me_button, back_button)
yes_keyboard = InlineKeyboardMarkup(row_width=1).add(yes_button)
close_dialog_keyboard = InlineKeyboardMarkup(row_width=1).add(close_dialog_button)
choice_settings_keyboard = InlineKeyboardMarkup(row_width=2).add(change_name_button, change_phone_button, back_button)
admin_main_menu_keyboard = InlineKeyboardMarkup(row_width=1).add(mailing_button, info_user_button, block_button)
home_keyboard = InlineKeyboardMarkup(row_width=1).add(home_button)
block_menu_keyboard = InlineKeyboardMarkup(row_width=2).add(unlock_user_button, block_user_button, home_button)
